name: regenerate documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  regenerate_docs:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
          persist-credentials: true

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26.1"

      - name: Install swag
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Regenerate docs
        run: |
          rm -rf docs/
          swag init -g cmd/trophy/main.go --parseInternal

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "docs: regenerate"
          file_pattern: "docs/"
